version: '3'
services:
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD
    restart: always
  web:
    build: .
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    depends_on:
      - db